### ISSUE TITLE
Archives Chapter

### ISSUE THREAD

**Issue by sehorowitz** [bmw9t/introduction-to-text-analysis#25]
I just added in some stuff that had some disciplinary content and more explanation of what NINES is, why it might be useful for students, etc. Let me know if this is what you were looking for and/or if you want me to add anything else!

**Comment by walshbr** [comment]
Awesome thanks! Question about the markdown syntax. Are you switching some of the italics as asterisk's to underlines?

**Hello** vs _hello_

My suspicion is that the editor might be making things wonky. Or maybe something is happening when you copy and paste? Are you still having to copy and paste a lot? In most cases it's not a big deal, since they parse the same way. But it seems like sometimes the change in formatting is making rogue _'s come through. Noticed it happening on stuff I had written too, so I think it's probably not something you did. Also noticed something similar with the NINES acronym - **(NINES)** became something like **\(\*\_NINES\\_\*)**. You get the idea - trying to escape all those slashes myself for the example was a little annoying. Is that you escaping all those characters in the text? Or just the editor?

**Comment by sehorowitz** [comment]
it's the editor, not me! no underlines or weird characters on my part!
