### ISSUE TITLE
Review Zotero exercises and lesson

### ISSUE THREAD

**Issue by walshbr** [bmw9t/introduction-to-text-analysis#31]

**Comment by sehorowitz** [comment]
looks great! I just added stuff in about needing to correct the citations in a lot of cases (primarily when pulling from a library catalog, since the capitalization is different than what you'd use with a bibliography). and I changed the exercises to have them add all the readings from this class b/c a) it's remotely possible they haven't written a research paper before and b) that way they'd already have them in their libraries for their final projects.

**Comment by walshbr** [comment]
Sounds awesome! And thoughts on zotero groups? Is that something they can trouble through on their own as part of the final projects? or would that require more coaching?

**Comment by sehorowitz** [comment]
i've never used them.  let me see if i can easily add you to see my stuff.

**Comment by sehorowitz** [comment]
short answer -- it's not that hard, but does require them to create a zotero account and will require a little bit of coaching. maybe it's something we show them when they are doing in the research for their final projects?

**Comment by walshbr** [comment]
We'll talk through how to do it in class but leave it out of the book.
