### ISSUE TITLE
review topic modeling exercises

### ISSUE THREAD

**Issue by walshbr** [bmw9t/introduction-to-text-analysis#45]
drafted. two more project critiques like in the last chapter.

**Comment by sehorowitz** [comment]
i'm wondering if the exercises are asking too much of the students, since it's essentially asking them to read the equivalent of another article and then answer a lot of questions, some of them which are difficult. so one option would be to just have them read the "Mining the Dispatch" (which has the advantage of talking about actual historical events as opposed to scholarly discourse. and, i think, it makes some good jumps from the data to what the data shows (i.e., how much you need to know to interpret topic modelling) and maybe ask them to answer, i dunno, four questions from the list of questions. thoughts? preferences? likes or dislikes?

**Comment by walshbr** [comment]
Sure thing. I updated it accordingly. Let me know what you think once it stops cooking.

**Comment by walshbr** [comment]
But I want them to do all the thiiiiiiiiiings

**Comment by sehorowitz** [comment]
i know! me too!
