### ISSUE TITLE
review classifying texts

### ISSUE THREAD

**Issue by walshbr** [bmw9t/introduction-to-text-analysis#51]
I wound up sticking JK Rowling at the end as a kind of payoff. Instead of focusing on her, I walk the students through how they might do a similar analysis themselves with authors from the syllabus.

**Comment by sehorowitz** [comment]
ok, i have some examples for the classification that would be 19th c material we've discussed in class. one is the String of Pearls, which was co-authored anonymously (that is to say, the authors are known and I think traded off chapter by chapter [so says Wikipedia]). the other is who was writing the articles on jack the ripper for the Pall Mall Gazette, which we'll talk about. i can find examples of the writings of the editor-in-chief and one of the other journalists online, so that could be a thing that they test. (but of course, to be honest, it's possible that it was entirely someone else.) let me know what you think and I'm happy to write either one up in this article or the exercise one.

**Comment by walshbr** [comment]
That sounds awesome. It'd be great to have that in there, if you want to tackle writing it. Are you thinking as replacement or supplement? I think it could work well to have them both be in there.

Also, in case you haven't looked at the exercises yet, I basically ask them to practice the same same authorship attribution thing on their own. Could ask them to take on that task themselves with those texts.

**Comment by sehorowitz** [comment]
ok, check out what i put in for the string of pearls example (which is in Classifying Texts). Basically, the tool had the text as uncertain, which a slight preference for one author (I think that they two traded off the writing of chapters, which means that the odd numbered chapters should match each other, which is true in this case). But I ended up saying that maybe the the uncertainty means that the authors had essentially the same style, perhaps a feature of the genre.
